# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/siqingxu/Desktop/Comp541/Comp541/Lab5/Lab5.cache/wt [current_project]
set_property parent.project_path /home/siqingxu/Desktop/Comp541/Comp541/Lab5/Lab5.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/siqingxu/Desktop/Comp541/Comp541/Lab5/Lab5.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  /home/siqingxu/Desktop/Comp541/Comp541/Lab5/Lab5.srcs/sources_1/imports/new/xycounter.sv
  /home/siqingxu/Desktop/Comp541/Comp541/Lab5/Lab5.srcs/sources_1/new/display640x480.sv
  /home/siqingxu/Desktop/Comp541/Comp541/Lab5/Lab5.srcs/sources_1/new/vgatimer.sv
  /home/siqingxu/Desktop/Comp541/Comp541/Lab5/Lab5.srcs/sources_1/new/vgadisplaydriver.sv
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/siqingxu/Desktop/Comp541/Comp541/Lab5/Lab5.srcs/constrs_1/new/clock.xdc
set_property used_in_implementation false [get_files /home/siqingxu/Desktop/Comp541/Comp541/Lab5/Lab5.srcs/constrs_1/new/clock.xdc]

read_xdc /home/siqingxu/Desktop/Comp541/Comp541/Lab5/Lab5.srcs/constrs_1/new/vga.xdc
set_property used_in_implementation false [get_files /home/siqingxu/Desktop/Comp541/Comp541/Lab5/Lab5.srcs/constrs_1/new/vga.xdc]


synth_design -top vgadisplaydriver -part xc7a100tcsg324-1


write_checkpoint -force -noxdef vgadisplaydriver.dcp

catch { report_utilization -file vgadisplaydriver_utilization_synth.rpt -pb vgadisplaydriver_utilization_synth.pb }
